# Generated by Django 3.2.8 on 2021-10-29 23:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music_data', '0003_remove_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='genreartist',
            name='export_date',
            field=models.PositiveBigIntegerField(default=int(datetime.datetime.utcnow().timestamp())),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genreartist',
            name='artist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='genre_artists', to='music_data.artist'),
        ),
        migrations.AlterField(
            model_name='genreartist',
            name='genre',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='genre_artists', to='music_data.genre'),
        ),
    ]
