# Generated by Django 3.2.8 on 2021-10-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_data', '0004_export_timestamp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='genreartist',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='genreartist',
            name='genre',
        ),
        migrations.AddField(
            model_name='genre',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='genreartist',
            name='artist_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='genreartist',
            name='genre_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='genreartist',
            name='export_date',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
