# Generated by Django 3.2.8 on 2021-10-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music_data", "0007_set_table_names"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="genreartist",
            unique_together={("genre_id", "artist_id")},
        ),
    ]
